version: '3.8'
services:
  gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    depends_on:
      - users-service
      - annonces-service
      - favoris-service
      - messaging-service
      - notifications-service
  users-service:
    build: ./users-service
    ports:
      - "8001:8001"
  annonces-service:
    build: ./annonces-service
    ports:
      - "8002:8002"
  favoris-service:
    build: ./favoris-service
    ports:
      - "8003:8003"
  messaging-service:
    build: ./messaging-service
    ports:
      - "8004:8004"
  notifications-service:
    build: ./notifications-service
    ports:
      - "8005:8005"
